/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppInput: typeof import('./components/AppInput.vue')['default']
    AppTextarea: typeof import('./components/AppTextarea.vue')['default']
    CopyButton: typeof import('./components/CopyButton.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    ResultRow: typeof import('./components/ResultRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegToggle: typeof import('./components/SegToggle.vue')['default']
    SideNav: typeof import('./components/SideNav.vue')['default']
    ToolPage: typeof import('./components/ToolPage.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
